name: Test

on:
  pull_request:
    types: [opened, synchronize]
  pull_request_target:
    types: [labeled]
  push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: (github.event_name != 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'run to test')) || contains(github.event.pull_request.labels.*.name, 'run to test')
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - Simple-KVS
        unityVersion:
          - 2021.3.15f1
          - 2022.1.23f1
        testMode:
          - playmode
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      - uses: webbertakken/unity-test-runner@v2.0.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        id: tests
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
